/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/actuator/health': {
        /** GET-метод, для контроля запуска сервиса в Kubernetes. */
        get: {
            responses: {
                /** @description null */
                200: {
                    content: {
                        'application/json': components['schemas']['BffActuatorResponse'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/client': {
        /** Данные пользователя с ФИО и телефоном */
        get: {
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffClient'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/files/template-salary': {
        /**
         * Получить файл шаблона зарплатной ведомости
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=315606590
         */
        get: {
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: never;
                };
            };
        };
    };
    '/api/v1/salaries/group-operations/{groupOperationId}': {
        /**
         * Получить результат групповой операции для ЗР
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=330219629
         */
        get: {
            parameters: {
                path: {
                    /** @description Идентификатор групповой операции */
                    groupOperationId: string;
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffCoreSalaryListGetGroupOperationStatusResponse'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/statuses/count': {
        /**
         * Получение количества ЗР в определенном статусе
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=315617858
         */
        get: {
            parameters: {
                query: {
                    /** @description Идентификатор организации */
                    organizationId: string;
                    /** @description Статус */
                    status?: string;
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffSalariesStatusesCount'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/reprocessing': {
        /**
         * Отправка ЗР на повторную обработку
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=318936622#expand-
         */
        post: {
            requestBody: {
                content: {
                    'application/json': {
                        /** @description Идентификатор документа */
                        id?: string;
                    };
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                204: {
                    content: {
                        'application/json': components['schemas']['BffSalariesReprocessing'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/sending-for-signing': {
        /**
         * Отправка ЗР в "Готов к подписанию"
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=312074771
         */
        post: {
            requestBody: {
                content: {
                    'application/json': {
                        /** @description Идентификаторы ЗР */
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffSalariesSendingForSigning'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/sending-signing': {
        /**
         * Отправка ЗР в "Подписание"
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=312082379#expand-200
         */
        post: {
            requestBody: {
                content: {
                    'application/json': {
                        /** @description Идентификаторы ЗР */
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffCoreSalaryListSendSigningResponse'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/cancel-signing': {
        /**
         * Отмена подписания ЗР
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=312081375#expand-
         */
        post: {
            requestBody: {
                content: {
                    'application/json': {
                        /** @description Идентификаторы ЗР */
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffSalariesCancelSigning'];
                    };
                };
            };
        };
    };
    '/api/v1/sign-verification': {
        /**
         * Проверка возможности подписания документа
         * @description https://wiki.domrf.ru/x/9rx3Dw
         */
        post: {
            parameters: {
                header: {
                    /** @description Заголовок "X-UserInfo" содержит в себе закодированный согласно RFC 5987 JSON-объект "UserInfo" */
                    'X-UserInfo': string;
                };
            };
            /** @description Запрос*/
            requestBody: {
                content: {
                    'application/json': components['schemas']['BffsignVerificationRequestBody'];
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/json': components['schemas']['BffSignVerificationResponseDto'];
                    };
                };
            };
        };
    };
    '/api/v2/salaries/print': {
        /**
         * Получение ПДФ ЗР (Bff)
         * @description https://wiki.domrf.ru/pages/viewpage.action?pageId=201384436#tab-v2
         */
        post: {
            requestBody: {
                content: {
                    'application/json': {
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Запрос обработан успешно */
                200: {
                    content: {
                        'application/zip': components['schemas']['BffsalariesPrint'];
                    };
                };
            };
        };
    };
    '/api/v1/salaries/file': {
        /**
         * Подтверждение импорта файлов ЗР
         * @description Подтверждение импорта файлов ЗР
         */
        put: operations['confirmSalaryRegistryImport_1'];
        /**
         * Импорт зарплатного реестра
         * @description Импортирует зарплатный реестр
         */
        post: operations['importSalaryLoader_1'];
        /**
         * Удаление зарплатных реестров по идентификаторам
         * @description Удалить зарплатный реестр вместе с распознанными реестрами
         */
        delete: operations['deleteSalaryRegistries_1'];
    };
    '/api/v1/salaries/file/{importFileId}/report': {
        /**
         * Получение excel-файла отчета по импортируемому ЗР
         * @description Возвращает excel-файл отчета по импортируемому ЗP
         */
        get: operations['getImportFileReport_1'];
    };
    '/api/v1/salaries': {
        /**
         * Поиск ЗР по набору фильтров
         * @description Возвращает список найденных зарплатных реестров, соответствующих переданному набору фильтров
         */
        get: operations['searchSalaryRegistries'];
        /**
         * Удаление одного/нескольких черновиков ЗР по ID
         * @description Удаляет один/несколько черновиков зарплатных реестров по их идентификаторам
         */
        delete: operations['deleteDraftSalaryRegistries'];
        /**
         * Смена статуса ЗР
         * @description Меняет статус зарплатного реестра с "DRAFT" на "FOR_SIGNING" или наоборот
         */
        patch: operations['changeSalaryRegistryStatus'];
    };
    '/api/v1/salaries/print': {
        /**
         * Получение ПДФ ЗР
         * @description Возвращает файл печатной формы зарплатного реестра
         */
        get: operations['printSalaryRegistry'];
    }
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        BffLoaderSalaryRegisterImportConfirmResponse: {
            /**
             *  Format: List
             * @description Наименования успешно отправленных файлов
             */
            fileNames: string[];
        };
        BffLoaderErrorMessage: {
            /** Format: uuid */
            id?: string;
            messages?: string[];
            /** Format: date-time */
            timestamp?: string;
        };
        BffLoaderSalaryRegisterImportConfirmRequest: {
            /**
             * Format: uuid
             * @description Идентификатор файла загрузки
             */
            importFileId?: string;
            /**
             * Format: int64
             * @description Размер импортируемого файла (в байтах)
             * @example 62
             */
            size?: number;
            /**
             * @description Имя импортируемого файла
             * @example file.txt
             */
            name?: string;
            /**
             * @description Состояние импортируемого файла
             * @example RECOGNIZED
             * @enum {string}
             */
            state?: 'PROCESSING' | 'RECOGNIZED' | 'UNRECOGNIZED' | 'SENT' | 'SENT_ERROR';
        };
        BffLoaderAccountsPK: {
            dateFormation: string;
            contractNumber: string;
            contractDate: string;
            nameOrganization: string;
            inn: string;
            bic: string;
            idFirstDocument: string;
            registryNumber: string;
            registrationDate: string;
            typeTransfer: string;
            requestInn: string;
            incomeTypeCode?: string;
            accountOrganization?: string;
            creditingSalary: components['schemas']['BffLoaderCreditingSalary'];
            checksums: components['schemas']['BffLoaderChecksums'];
        };
        BffLoaderChecksums: {
            numberRecords: string;
            totalAmount: string;
        };
        BffLoaderCreditingSalary: {
            employee: components['schemas']['BffLoaderEmployee'][];
        };
        BffLoaderEmployee: {
            npp: string;
            surname: string;
            name: string;
            middleName?: string;
            personalAccount: string;
            amount: string;
            currencyCode: string;
            withholdAmount?: string;
        };
        BffLoaderMetricNamesDescriptor: {
            names?: string[];
        };
        BffLoaderAvailableTag: {
            tag?: string;
            values?: string[];
        };
        BffLoaderMetricDescriptor: {
            name?: string;
            description?: string;
            baseUnit?: string;
            measurements?: components['schemas']['BffLoaderSample'][];
            availableTags?: components['schemas']['BffLoaderAvailableTag'][];
        };
        BffLoaderSample: {
            /**
             * @enum {string}
             */
            statistic?: 'TOTAL' | 'TOTAL_TIME' | 'COUNT' | 'MAX' | 'VALUE' | 'UNKNOWN' | 'ACTIVE_TASKS' | 'DURATION';
            /**
             * Format: double
             */
            value?: number;
        };
        BffLoaderHealthComponent: Record<string, never>;
        /**
         * Format: List
         * @description Идентификатор зарплатного реестра
         * @example ["3a883eb6-2f63-4f8d-a74a-e478a452edb0", "4a883eb6-2f63-4f8d-a74a-e478a452edb0"]
         */
        BffLoaderSalaryParsedRegisterDeleteRequest: {
            importFileId: string[];
        };
        /** @description Запрос на получение одного/нескольких ПДФ зарплатного реестра */
        BffCoreSalaryListPrintRequest: {
            ids: string[];
        };
        BffCoreErrorMessage: {
            /**
             * Format: uuid
             */
            id?: string;
            messages?: string[];
            /**
             * Format: date-time
             */
            timestamp?: string;
        };
        BffCoreSalaryListUploadResponse: {
            /**
             * Format: uuid
             */
            storageId: string;
            docName: string;
        };
        BffCoreSendSalaryRegistryToWay4Request: {
            /**
             * Format: uuid
             * @description Идентификатор ЗР
             */
            id: string;
        };
        /** @description Запрос на отправку одного/нескольких ЗР в "Подписание" */
        BffCoreSalaryListSendSigningRequest: {
            ids: string[];
        };
        /** @description Данные о результатах проверки документа ЗР */
        BffCoreCheckDocumentResult: {
            /**
             * Format: uuid
             * @description Идентификатор ЗР
             * @example 573f11bd-fdc4-40d0-b87d-f4b19cd3999a
             */
            id: string;
            /**
             * Format: int32
             * @description Номер ЗР
             * @example 115
             */
            number: number;
            /**
             * Format: date
             * @description Дата ЗР
             * @example 2024-09-27
             */
            date: string;
            /**
             * @description Имя файла реестра
             * @example 00032-1223-123.xls
             */
            fileName: string;
            /**
             * @description Сумма по реестру
             * @example 1000
             */
            amount: number;
            violations?: string[];
        };
        /** @description Данные о результатах проверки набора документов ЗР */
        BffCoreCheckDocumentsResults: {
            /**
             * Format: int32
             * @description Общее количество документов
             * @example 2
             */
            totalCount: number;
            /**
             * Format: int32
             * @description Количество документов, недоступных для смены статуса
             * @example 1
             */
            notAvailableCount: number;
            /**
             * Format: int32
             * @description Количество документов, доступных для смены статуса
             * @example 1
             */
            availableCount: number;
            notAvailableDocuments: components['schemas']['BffCoreCheckDocumentResult'][];
            availableDocuments: components['schemas']['BffCoreCheckDocumentResult'][];
        };
        /** @description Ответ на запрос отправки одного/нескольких ЗР в процесс перевода в статус "Подписание" */
        BffCoreSalaryListSendSigningResponse: {
            /**
             * @description Отправлено в "Подписание"
             * @example true
             */
            isSentSigning: boolean;
            /**
             * Format: uuid
             * @description Идентификатор групповой операции
             * @example fbe1d5ac-85e3-4242-a9a8-7f11abd4c81f
             */
            groupOperationId?: string;
            /**
             * @description Тип подписи
             * @enum {string}
             */
            signatureSystem?: string;
            checkResult?: components['schemas']['BffCoreCheckDocumentsResults'];
        };
        /** @description Запрос на отправку одного/нескольких ЗР в "Готов к подписанию" */
        BffCoreSalaryListSendForSigningRequest: {
            ids: string[];
        };
        /** @description Ответ на запрос отправки одного/нескольких ЗР в процесс перевода в статус "Готов к подписанию" */
        BffCoreSalaryListSendForSigningResponse: {
            /**
             * @description Отправлено в "Готов к подписанию"
             * @example true
             */
            isSentForSigning: boolean;
            /**
             * Format: uuid
             * @description Идентификатор групповой операции
             * @example fbe1d5ac-85e3-4242-a9a8-7f11abd4c81f
             */
            groupOperationId?: string;
            checkResult?: components['schemas']['BffCoreCheckDocumentsResults'];
        };
        /**
         * Format: uuid
         * @description Идентификатор ЗР
         */
        BffCoreSendEmailToEmployeeRequest: {
            id: string;
        };
        /** @description Запрос на отправку ЗР на повторную обработку */
        BffCoreSalaryReprocessingRequest: {
            /**
             * Format: uuid
             * @description Идентификатор зарплатного реестра
             * @example 3a883eb6-2f63-4f8d-a74a-e478a452edbe
             */
            id: string;
        };
        /** @description Запрос на загрузку шаблона */
        BffCoreSalaryTemplateRequest: {
            /**
             * @description Имя файла
             * @example fileName
             */
            fileName: string;
            /**
             * @description Файл в формате base64
             * @example 3a883eb652f63V4f8dAa74aSe478a452edbe
             */
            fileContent: string;
        };
        /** @description Запрос на отмену подписания ЗР */
        BffCoreSalaryListCancelSigningRequest: {
            ids: string[];
        };
        /** @description Ответ на запрос отмены подписания ЗР */
        BffCoreSalaryListCancelSigningResponse: {
            /**
             * @description Подписание отменено
             * @example true
             */
            isCancelSigning: boolean;
            /**
             * Format: uuid
             * @description Идентификатор групповой операции
             * @example fbe1d5ac-85e3-4242-a9a8-7f11abd4c81f
             */
            groupOperationId?: string;
        };
        /** @description Статус зарплатного реестра */
        BffCoreChangeSalaryStatusRequest: {
            /**
             * @description Целевой статус
             * @enum {string}
             */
            status: 'DRAFT' | 'FOR SIGNING' | 'PROCESSING' | 'EXECUTED' | 'REJECTED' | 'SIGNING' | 'WAITING PAYMENT';
        };
        /** @description Запрос на смену статуса операции ЗР */
        BffCoreSalaryListChangeOperationStatusRequest: {
            /**
             * @description Статус операции
             * @example COMPLETED
             * @enum {string}
             */
            status: 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';
            /**
             * @description Детали ошибки
             * @example Ошибка подписания документа
             */
            errorDetails?: string;
            /**
             * Format: uuid
             * @description Идентификатор операции подписания ПЭП
             * @example 1f8c14a2-ce82-48f8-b3d5-61df89b2d938
             */
            signOperationId?: string;
        };
        BffCoreCheckSalaryImportPossibilityResponse: {
            /** Format: uuid */
            organizationId?: string;
            fileName?: string;
            canImport?: boolean;
            message?: string;
        };
        /** @description Запрос поиска ЗР по набору фильтров */
        BffCoreSalaryListSearchRequest: {
            [key: string]: unknown;
        };
        Organization: {
            id: string;
            name: string;
            inn: string;
            email: string;
            employeePosition: string;
        };
    };
}
